require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SwypOutsController do

  # This should return the minimal set of attributes required to create a valid
  # SwypOut. As you add validations to SwypOut, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all swyp_outs as @swyp_outs" do
      swyp_out = SwypOut.create! valid_attributes
      get :index
      assigns(:swyp_outs).should eq([swyp_out])
    end
  end

  describe "GET show" do
    it "assigns the requested swyp_out as @swyp_out" do
      swyp_out = SwypOut.create! valid_attributes
      get :show, :id => swyp_out.id.to_s
      assigns(:swyp_out).should eq(swyp_out)
    end
  end

  describe "GET new" do
    it "assigns a new swyp_out as @swyp_out" do
      get :new
      assigns(:swyp_out).should be_a_new(SwypOut)
    end
  end

  describe "GET edit" do
    it "assigns the requested swyp_out as @swyp_out" do
      swyp_out = SwypOut.create! valid_attributes
      get :edit, :id => swyp_out.id.to_s
      assigns(:swyp_out).should eq(swyp_out)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SwypOut" do
        expect {
          post :create, :swyp_out => valid_attributes
        }.to change(SwypOut, :count).by(1)
      end

      it "assigns a newly created swyp_out as @swyp_out" do
        post :create, :swyp_out => valid_attributes
        assigns(:swyp_out).should be_a(SwypOut)
        assigns(:swyp_out).should be_persisted
      end

      it "redirects to the created swyp_out" do
        post :create, :swyp_out => valid_attributes
        response.should redirect_to(SwypOut.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved swyp_out as @swyp_out" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwypOut.any_instance.stub(:save).and_return(false)
        post :create, :swyp_out => {}
        assigns(:swyp_out).should be_a_new(SwypOut)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwypOut.any_instance.stub(:save).and_return(false)
        post :create, :swyp_out => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested swyp_out" do
        swyp_out = SwypOut.create! valid_attributes
        # Assuming there are no other swyp_outs in the database, this
        # specifies that the SwypOut created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SwypOut.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => swyp_out.id, :swyp_out => {'these' => 'params'}
      end

      it "assigns the requested swyp_out as @swyp_out" do
        swyp_out = SwypOut.create! valid_attributes
        put :update, :id => swyp_out.id, :swyp_out => valid_attributes
        assigns(:swyp_out).should eq(swyp_out)
      end

      it "redirects to the swyp_out" do
        swyp_out = SwypOut.create! valid_attributes
        put :update, :id => swyp_out.id, :swyp_out => valid_attributes
        response.should redirect_to(swyp_out)
      end
    end

    describe "with invalid params" do
      it "assigns the swyp_out as @swyp_out" do
        swyp_out = SwypOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwypOut.any_instance.stub(:save).and_return(false)
        put :update, :id => swyp_out.id.to_s, :swyp_out => {}
        assigns(:swyp_out).should eq(swyp_out)
      end

      it "re-renders the 'edit' template" do
        swyp_out = SwypOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwypOut.any_instance.stub(:save).and_return(false)
        put :update, :id => swyp_out.id.to_s, :swyp_out => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested swyp_out" do
      swyp_out = SwypOut.create! valid_attributes
      expect {
        delete :destroy, :id => swyp_out.id.to_s
      }.to change(SwypOut, :count).by(-1)
    end

    it "redirects to the swyp_outs list" do
      swyp_out = SwypOut.create! valid_attributes
      delete :destroy, :id => swyp_out.id.to_s
      response.should redirect_to(swyp_outs_url)
    end
  end

end
